# Generated by Django 3.1.1 on 2020-09-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200911_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_at']},
        ),
    ]
