# Generated by Django 3.1.1 on 2020-09-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
