# Generated by Django 3.1.1 on 2020-09-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='bipolar_disorder',
            new_name='bipolar',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='empathy_deficit_disorder',
            new_name='empathy_deficit',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='sleep_disorder',
            new_name='sleep',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='social_anxiety_disorder',
            new_name='social_anxiety',
        ),
    ]
