# Generated by Django 3.1.1 on 2020-09-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200912_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='bipolar',
            new_name='bipolar_disorder',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='empathy_deficit',
            new_name='empathy_deficit_disorder',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='sleep',
            new_name='sleep_disorder',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='social_anxiety',
            new_name='social_anxiety_disorder',
        ),
    ]
